site_name: Manoj in Binary Land
site_url: https://manojbaasha.github.io/blog/
site_author: Manoj Elango
site_description: >-
  Welcome to Binary Land where I share my experience in coding and some of my thoughts and opinions in newer technologies, tools and frameworks!

# Repository
repo_name: ManojBaasha/blog
repo_url: https://github.com/ManojBaasha/blog

plugins:
  - blog:
      blog_dir: blog 
      blog_toc: true
  - search
  - tags
  
  
nav:
  - Home: index.md
  - About: about.md
  - Blog:
    - blog/index.md

theme:
    name: material
    palette:
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

        # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    font:
      text: Fira Code
    features:
      - navigation.top
    

    
